version: '3.9'

services:

  js-sms-worker:
    build: .
    container_name: js-sms-worker
    environment:
      - REDIS_URL=redis://ussd-redis:6379
      - SMPP_HOST=messaging.airtel.cd
      - SMPP_PORT=9001
      - SMPP_SYSTEM_ID=AirtelQuiz
      - SMPP_PASSWORD=@irtElq1 

    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true