version: '3.9'

services:

  js-sms-worker:
    build: .
    container_name: js-sms-worker 
    command: node src/worker.js
    networks:
      - dokploy-network

  js-sms-worker-api:
    build: .
    container_name: js-sms-worker-api 
    expose:
      - "3000"
    command: node src/server.js
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true